import turtle

monty = turtle.Turtle()
monty.shape("turtle")

monty.penup()
monty.goto(-200, 200)
monty.pendown()
monty.color("blue")
monty.fillcolor("blue")
monty.begin_fill()
monty.forward(400)
monty.right(90)
monty.forward(400)
monty.right(90)
monty.forward(400)
monty.right(90)
monty.forward(400)
monty.right(90)
monty.end_fill()
monty.penup()
monty.goto(0, 0)
monty.pendown()
monty.color("blue")
monty.fillcolor("blue")
monty.begin_fill()
monty.circle(200)
monty.end_fill()
